---
apiVersion: v1
kind: Service
metadata:
  name: hostel-allocation
  namespace: hostel-allocation
  labels:
    app: hostel-allocation
spec:
  type: LoadBalancer
  selector:
    app: hostel-allocation
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
